import {StyleSheet} from 'react-native'
export default StyleSheet.create({
    imgBody:{
        resizeMode:'contain',
        width:undefined,
        height:410
    },
    containIcon:{
        flexDirection:'row',
        marginTop:8
    },
    bookmark:{
        flex:1,
        alignItems:'flex-end',
        marginHorizontal:16
    },
    imgLike:{
        height:20,
        width:20,
        borderRadius:30
    },
    infoLike:{
        flexDirection:'row',
        marginTop:8,
        marginHorizontal:16
    },
    nameUser:{
        fontWeight:'bold',
        marginRight:8
    },
    containStatus:{
        flexDirection:'row',
        marginLeft:16,
        marginTop:8
    },
    imgava:{
        width:35,
        height:35,
        borderRadius:300,
        marginBottom:8,
        marginLeft:12,
        marginTop:8
    },
    contain:{
        flexDirection:'row',
        borderBottomWidth:0.5,
        flex:1
    },
    name:{
        alignItems:'center',
        marginLeft:8,
        flexDirection:'row'
    },
    nameNV:{
        fontWeight:'bold'
    },
    containImg:{
        flexDirection:'row'
    }
})